[phases.setup]
nixPkgs = [
  "...",
  "chromium",
  "libnss3",
  "libatk-bridge2.0-0",
  "libdrm2",
  "libxcomposite1",
  "libxdamage1",
  "libxrandr2",
  "libgbm1",
  "libasound2",
  "libpango-1.0-0",
  "libcairo2",
  "libcups2",
  "libxss1",
  "libgtk-3-0"
]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
